name: Run Kotlin Script on Merge to Main

on:
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - main
  push:
    branches:
      - run-script

jobs:
  run-kotlin-script:
    # if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '23'

      - name: Show current directory
        run: ls -la

      # - name: Download Kotlin Script
      #   run: |
      #     curl -L -o script.kts https://raw.githubusercontent.com/username/repository/branch/path/to/script.kts

      - name: Run Kotlin Script via kotlinc
        run: |
          kotlinc -script script.kts

      - name: Run Kotlin Script directly
        run: |
          ./script.kts
